---
sidebar: sidebar 
permalink: concept_api_rest.html 
keywords: rest api, deploy rest api, rest, architecture, resources, state, uri, http, json 
summary: '表述性状态传输 (REST) 是一种用于创建分布式 Web 应用程序的样式。当应用于 Web 服务 API 的设计时，它可以建立一套用于公开基于服务器的资源并管理其状态的技术和最佳实践。它使用主流协议和标准，为部署和管理ONTAP Select集群提供灵活的基础。' 
---
= 用于部署和管理ONTAP Select集群的 REST Web 服务基础
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
表述性状态传输 (REST) 是一种用于创建分布式 Web 应用程序的样式。当应用于 Web 服务 API 的设计时，它可以建立一套用于公开基于服务器的资源并管理其状态的技术和最佳实践。它使用主流协议和标准，为部署和管理ONTAP Select集群提供灵活的基础。



== 建筑与经典约束

REST 理论由 Roy Fielding 在其博士论文中正式阐述。 https://www.ics.uci.edu/~fielding/pubs/dissertation/top.htm["论文"] 2000年毕业于加州大学尔湾分校。它通过一系列约束定义了一种架构风格，这些约束共同改进了基于Web的应用程序及其底层协议。这些约束基于客户端/服务器架构，使用无状态通信协议，构建了一个RESTful Web服务应用程序。



== 资源和国家代表

资源是基于 Web 系统的基本组件。创建 REST Web 服务应用程序时，早期设计任务包括：

* 识别系统或基于服务器的资源。每个系统都会使用和维护资源。资源可以是文件、业务事务、流程或管理实体。基于 REST Web 服务设计应用程序的首要任务之一就是识别资源。
* 资源状态及相关状态操作的定义：资源始终处于有限数量的状态之一。必须明确定义这些状态以及用于影响状态变化的相关操作。


客户端和服务器之间交换消息，根据通用 CRUD（创建、读取、更新和删除）模型访问和更改资源的状态。



== URI 端点

每个 REST 资源都必须使用定义明确的寻址方案进行定义和提供。资源所在和标识的端点使用统一资源标识符 (URI)。URI提供了一个通用框架，用于为网络中的每个资源创建唯一名称。统一资源定位符 (URL) 是一种用于 Web 服务识别和访问资源的 URI。资源通常以类似于文件目录的层级结构公开。



== HTTP 消息

超文本传输协议 (HTTP) 是 Web 服务客户端和服务器用来交换资源请求和响应消息的协议。在设计 Web 服务应用程序的过程中，HTTP 动词（例如 GET 和 POST）会被映射到资源及其对应的状态管理操作。

HTTP 是无状态的。因此，为了将一组相关的请求和响应关联到一个事务下，必须在请求/响应数据流携带的 HTTP 标头中包含附加信息。



== JSON 格式

虽然信息可以通过多种方式在客户端和服务器之间构建和传输，但最流行的选项（以及与部署 REST API 一起使用的选项）是 JavaScript 对象表示法 (JSON)。JSON是一种行业标准，用于以纯文本表示简单数据结构，并用于传输描述资源的状态信息。
