---
sidebar: sidebar 
permalink: concept_adm_before.html 
keywords: administer, administering, web, before you begin 
summary: 创建ONTAP Select集群后，您可以通过执行各种管理任务来支持部署。以下是一些需要注意的一般事项。 
---
= 开始管理ONTAP Select之前
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
创建ONTAP Select集群后，您可以通过执行各种管理任务来支持部署。以下是一些需要注意的一般事项。

一般来说，使用 Deploy Web 界面可以执行的程序分为三类。

.部署ONTAP Select集群
您可以部署单节点或多节点集群。看link:task_deploy_cluster.html["部署ONTAP Select集群"]了解更多信息。

.使用现有ONTAP Select集群执行程序
管理程序分为不同的类别，例如“安全”和“集群”。

.在部署实用程序上执行一个过程
有几个特定于 Deploy 的程序（例如更改管理员的密码）。



== 管理ONTAP Select

作为ONTAP Select支持的一部分，有许多不同的管理程序可用。此外，还有一些特定于 Deploy 管理实用程序的程序。下面介绍其中最重要的程序。通常，所有程序都使用 Deploy Web 用户界面。


NOTE: 你也可以link:https://docs.netapp.com/us-en/ontap-select/task_cli_signing_in.html["使用命令行界面"]管理ONTAP Select。



== 执行额外的ONTAP配置

部署ONTAP Select集群后，您可以像管理基于硬件的ONTAP系统一样配置和管理该集群。例如，您可以使用ONTAP System Manager 或ONTAP CLI 来配置ONTAP Select集群。

.NetApp客户端软件
您可以使用以下受支持的NetApp客户端软件连接到ONTAP Select ：

* ONTAP System Manager
* Active IQ Unified Manager
* OnCommand Insight
* OnCommand Workflow Automation
* SnapCenter
* 适用于 VMware vSphere 的 Virtual Storage Console


要确定支持的客户端软件版本，请查看以下内容：link:https://mysupport.netapp.com/matrix/["互操作性表工具"^] 。如果客户端软件支持ONTAP 9，则ONTAP Select也支持相同版本。


NOTE: 使用SnapCenter及其相应的插件需要基于服务器的许可证。ONTAP Select目前不支持SnapCenter插件的存储系统许可。

ONTAP Select不支持列表中未包含的任何其他NetApp客户端软件。

.可能的配置选项
配置集群时有多个可用选项，其中包括：

* 创建网络配置
* 布置你的聚合体
* 创建数据存储虚拟机 (SVM)


.购买具有存储容量的许可证
如果您决定在部署ONTAP Select集群时不安装具有存储容量的许可证文件，则必须在使用购买的许可证运行的集群的宽限期到期之前获取并安装许可证文件。

.镜像聚合
Deploy 管理实用程序会从可用的数据存储空间（例如 Pool0 和 Pool1）在每个ONTAP Select节点上创建数据备用磁盘。要在多节点集群上实现数据的高可用性，您必须使用这些备用磁盘创建镜像聚合。


NOTE: 仅当数据聚合配置为镜像聚合时，才支持高可用性接管。
