---
sidebar: sidebar 
permalink: concept_api_operation.html 
keywords: rest api, deploy rest api, rest, operation, basic operation 
summary: 虽然 REST 确立了一套通用的技术和最佳实践，但每个 API 的细节可能会因设计选择而异。在使用ONTAP Select Deploy API 之前，您应该了解该 API 的详细信息和操作特性。 
---
= ONTAP Select Deploy API 基本操作特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
虽然 REST 确立了一套通用的技术和最佳实践，但每个 API 的细节可能会因设计选择而异。在使用ONTAP Select Deploy API 之前，您应该了解该 API 的详细信息和操作特性。



== 虚拟机管理程序主机与ONTAP Select节点

_虚拟机管理程序主机_是托管ONTAP Select虚拟机的核心硬件平台。当ONTAP Select虚拟机部署在虚拟机管理程序主机上并处于活动状态时，该虚拟机将被视为 ONTAP Select 节点。在 Deploy REST API 版本 3 中，主机对象和节点对象是独立且不同的。这允许一对多关系，其中一个或多个ONTAP Select节点可以在同一虚拟机管理程序主机上运行。



== 对象标识符

每个资源实例或对象在创建时都会分配一个唯一标识符。这些标识符在ONTAP Select Deploy 的特定实例中是全局唯一的。在发出创建新对象实例的 API 调用后，关联的 id 值将返回给调用者。 `location` HTTP响应头。您可以提取标识符，并在后续调用中引用资源实例时使用它。


NOTE: 对象标识符的内容和内部结构可能随时更改。在引用关联对象时，应仅在适用的 API 调用中根据需要使用这些标识符。



== 请求标识符

每个成功的 API 请求都会被分配一个唯一的标识符。返回的标识符 `request-id`相关HTTP响应的头部。您可以使用请求标识符来统称单个特定 API 请求-响应事务的活动。例如，您可以根据请求 ID 检索事务的所有事件消息。



== 同步和异步调用

服务器执行从客户端收到的 HTTP 请求主要有两种方式：

* 同步服务器立即执行请求并以状态代码 200、201 或 204 进行响应。
* 异步：服务器接受请求并以状态码 202 进行响应。这表示服务器已接受客户端请求并启动后台任务以完成该请求。最终的成功或失败情况无法立即确定，必须通过其他 API 调用来确定。




== 确认长期运行作业的完成

通常，任何需要很长时间才能完成的操作都会使用服务器上的后台任务异步处理。使用 Deploy REST API，每个后台任务都由一个 Job 对象固定，该对象跟踪任务并提供信息（例如当前状态）。创建后台任务后，HTTP 响应中会返回一个 Job 对象（包含其唯一标识符）。

您可以直接查询 Job 对象来确定相关 API 调用是否成功。有关更多信息，请参阅_使用 Job 对象进行异步处理_。

除了使用 Job 对象之外，还有其他方法可以确定请求的成功或失败，包括：

* 事件消息您可以使用原始响应返回的请求 ID 检索与特定 API 调用关联的所有事件消息。事件消息通常包含成功或失败的指示，在调试错误情况时也很有用。
* 资源状态或状况 一些资源维持一个状态或状况值，您可以查询该状态或状况值来间接确定请求的成功或失败。




== 安全性

Deploy API 使用以下安全技术：

* 传输层安全性 (TLS)：Deploy 服务器和客户端之间通过网络发送的所有流量均通过 TLS 加密。不支持在未加密的通道上使用 HTTP 协议。支持 TLS 1.2 版本。
* HTTP 身份验证 每个 API 事务都使用基本身份验证。每个请求都会添加一个 HTTP 标头，其中包含以 base64 字符串形式表示的用户名和密码。

