---
sidebar: sidebar 
permalink: concept_nw_concepts_chars.html 
keywords: ontap select, networking concepts, cluster characteristics 
summary: 首先熟悉适用于ONTAP Select环境的常规网络概念。然后，探索单节点和多节点集群的具体特性和选项。 
---
= ONTAP Select网络概念和特性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
首先熟悉适用于ONTAP Select环境的常规网络概念。然后，探索单节点和多节点集群的具体特性和选项。



== 物理网络

物理网络主要通过提供底层第二层交换基础架构来支持ONTAP Select集群部署。与物理网络相关的配置包括虚拟机管理程序主机和更广泛的交换网络环境。



=== 主机 NIC 选项

每个ONTAP Select虚拟机管理程序主机必须配置两个或四个物理端口。具体配置取决于以下几个因素：

* 集群是否包含一个或多个ONTAP Select主机
* 使用什么虚拟机管理程序操作系统
* 如何配置虚拟交换机
* 链路是否使用 LACP




=== 物理交换机配置

您必须确保物理交换机的配置支持ONTAP Select部署。物理交换机与基于虚拟机管理程序的虚拟交换机集成在一起。您选择的具体配置取决于多种因素。主要考虑因素包括：

* 您将如何保持内部和外部网络之间的分离？
* 您会保持数据和管理网络之间的分离吗？
* 二层 VLAN 将如何配置？




== 逻辑网络

ONTAP Select使用两个不同的逻辑网络，根据类型分离流量。具体来说，流量可以在集群内的主机之间流动，也可以流向集群外的存储客户端和其他计算机。虚拟机管理程序管理的虚拟交换机有助于支持逻辑网络。



=== 内部网络

在多节点集群部署中，各个ONTAP Select节点使用独立的“内部”网络进行通信。此网络不会暴露给ONTAP Select集群中的节点，也不会在节点外部使用。


NOTE: 内部网络仅存在于多节点集群中。

内部网络具有以下特点：

* 用于处理ONTAP集群内流量，包括：
+
** 集群
** 高可用性互连 (HA-IC)
** RAID 同步镜像 (RSM)


* 基于VLAN的单二层网络
* 静态 IP 地址由ONTAP Select分配：
+
** 仅限 IPv4
** 未使用 DHCP
** 链路本地地址


* MTU 大小默认为 9000 字节，可在 7500-9000 范围内调整（含）




=== 外部网络

外部网络处理ONTAP Select集群节点与外部存储客户端以及其他计算机之间的流量。外部网络是每个集群部署的一部分，具有以下特点：

* 用于处理ONTAP流量，包括：
+
** 数据（NFS、CIFS、iSCSI）
** 管理（集群和节点；可选 SVM）
** 集群间（可选）


* 可选支持 VLAN：
+
** 数据端口组
** 管理端口组


* 根据管理员的配置选择分配的 IP 地址：
+
** IPv4 或 IPv6


* MTU 大小默认为 1500 字节（可调整）


外部网络存在各种规模的集群。



== 虚拟机网络环境

虚拟机管理程序主机提供了多种网络功能。

ONTAP Select依赖于通过虚拟机公开的以下功能：

虚拟机端口:: ONTAP Select有多个端口可供使用。这些端口的分配和使用取决于多种因素，包括集群的大小。
虚拟交换机:: 虚拟机管理程序环境中的虚拟交换机软件（无论是 vSwitch (VMware) 还是 Open vSwitch (KVM)）都会将虚拟机公开的端口与物理以太网 NIC 端口连接起来。您必须根据环境为每个ONTAP Select主机配置一个 vSwitch。

