---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: 您可以购买三个平台容量级别之一的ONTAP Select容量层或容量池许可证。这些许可证决定了部署ONTAP Select 的主机的功能。 
---
= 了解ONTAP Select的平台许可证产品
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以购买标准级、高级或高级 XL 级ONTAP Select容量层或容量池许可证。这些许可证决定了部署ONTAP Select 的主机的功能。



== 平台许可证产品提供什么

特定的许可证方案决定了虚拟机管理程序主机在以下两个方面的功能：

* 实例类型（CPU、内存）
* 附加功能


许可证产品按功能从标准版到高级版 XL 的升序排列。通常，您选择的许可证选项会授予您该级别及所有较低级别的功能。例如，高级版同时提供高级版和标准版的功能。

下表比较了标准版、高级版和高级 XL 版许可证的功能。

[cols="25,25,25,25,25"]
|===
2+| 许可证支持…… | 标准 | 高级 | 高级加大码 


2+| 实例类型 | 仅限小型 | 小号或中号 | 小号、中号或大号 


.2+| 硬盘驱动器 (HDD) 在…… | 硬件 RAID 配置 | 是 | 是 | 是 


| vNAS 配置 | 是 | 是 | 是 


.3+| 固态硬盘 (SSD) 在…… | 硬件 RAID 配置 | 否 | 是 | 是 


| 软件 RAID 配置 | 否 | 是 | 是 


| vNAS 配置 | 是 | 是 | 是 


.3+| NVMe 驱动器在... | 硬件 RAID 配置 | 否 | 否 | 是 


| 软件 RAID 配置 | 否 | 否 | 是 


| vNAS 配置 | 是 | 是 | 是 


2+| MetroCluster SDS | 否 | 是 | 是 
|===

NOTE: 基于内核的虚拟机 (KVM) 不支持大型实例类型。



== 比较平台许可证产品的硬件支持

标准版、高级版和高级 XL 许可证产品支持多种硬件和软件。有关硬件和软件版本的最新信息，请参阅link:https://mysupport.netapp.com/matrix/["互操作性表工具"^]。

[role="tabbed-block"]
====
.核心物品
--
[cols="5"30"]
|===


2+| 核心物品类型 3+| 描述 


2+| 主机协议 3+| NFS、SMB/CIFS、iSCSI 和 NVMe over TCP 


2+| 部署选项 3+| 单节点 双节点集群（HA 对） 四节点、六节点或八节点集群 


2+| 支持的容量（每个节点） 3+| 高达 400TB 原始数据（ESXi 和 KVM） 
|===
--
.硬件
--
[cols="5"30"]
|===


2+| 硬件类型 3+| 描述 


2+| 实例大小 | 小型 | 中 | 大型 


2+| CPU系列 | Intel Xeon E5-26xx v3 (Haswell) 或更高版本 | Intel Xeon E5-26xx v3 (Haswell) 或更高版本 | Intel Xeon E5-26xx v3 (Haswell) 或更高版本 


2+| ONTAP SelectCPU/内存 | 4 个虚拟 CPU (vCPU) / 16GB RAM | 8 个 vCPU / 64GB RAM | 16 个 vCPU / 128GB RAM 


2+| 主机 CPU/内存最低要求^1^ | 6 核/24GB RAM | 10 核/72GB RAM | 18 核/136GB RAM 


2+| 网络（每个节点） 3+| 单节点集群至少有两个 1GbE 端口 双节点集群（HA 对）至少有四个 1GbE 端口 四节点、六节点或八节点集群至少有两个 10GbE 端口 
|===
^1^ 假设虚拟机管理程序有两个核心和 8GB RAM。

--
.存储类型
--
下表提供了指定存储所需的最低许可证类型。 

[cols="5"30"]
|===


2+| 存储类型 3+| 描述 


2+| 许可证类型 | 标准 | 高级 | 高级加大码 


2+| 实例大小 | 小型 | 小型和中型 | 小、中、大 


2+| 带有硬件 RAID 控制器的本地 DAS | 8 - 60 个驱动器 | 8 - 60 个驱动器 | 8 - 60 个驱动器 


2+| 硬盘 (SAS、NL-SAS、SATA) | 不适用 | 4 – 60 个驱动器 | 4 – 60 个驱动器 


2+| 固态硬盘 (SAS) | 不适用 | 4 – 60 个驱动器（仅限 SSD） | 4 – 60 个驱动器（仅限 SSD） 


2+| 带有软件 RAID 的本地 DAS | 不适用 | 适用的 | 4 - 14 个驱动器（仅限 NVMe） 


2+| 外部数组^1^ 3+| 托管在外部阵列上的数据存储通过 FC、FCoE、iSCSI 和 NFS（KVM 不支持 NFS）连接。这些数据存储提供高可用性和弹性。 
|===
^1^ 外部阵列协议支持反映了网络存储连接。

--
.软件
--
[cols="5"30"]
|===


2+| 软件类型 3+| 描述 


2+| 虚拟机管理程序支持 (VMware) 3+| VMware vSphere 9.0、VMware vSphere 8.0GA 及更新 1 至 3、VMware vSphere 7.0GA 及更新 1 至 3C 


2+| 虚拟机管理程序支持 (KVM)  a| 
Red Hat Enterprise Linux (RHEL) 64 位 (KVM) 10.0、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.8、8.7 和 8.6

Rocky Linux (KVM) 10.0、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7 和 8.6

*注意*：在 RHEL 10.0 和 Rocky Linux 10.0 主机上，KVM 虚拟机管理程序存在软件 RAID 工作流程限制。更多信息，请参阅以下知识库文章：

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020： ONTAP Select Deploy：使用 RHEL 10 和 ROCKY 10 创建集群 HWR 时出现警告消息"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025： ONTAP Select DeployGUI：在运行 RHEL10/Rocky 10 的主机上，集群创建页面中 SWR 的存储池和存储磁盘不可见"^]




2+| 管理软件 3+| NetApp Active IQ Unified Manager管理套件ONTAP Select Deploy Utility SnapCenter （可选） 
|===
--
====
.相关信息
* link:concept_lic_production.html["了解容量层和容量池许可证类型"]

