---
sidebar: sidebar 
permalink: concept_stor_eff_support.html 
keywords: ontap select, storage efficiency support 
summary: ONTAP Select提供的存储效率选项与FAS和AFF阵列上的存储效率选项类似。 
---
= ONTAP Select存储效率支持
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select提供的存储效率选项与FAS和AFF阵列上的存储效率选项类似。

使用全闪存 VSAN 或通用闪存阵列的ONTAP Select虚拟 NAS (vNAS) 部署应遵循具有非 SSD 直连存储 (DAS) 的ONTAP Select的最佳实践。

只要您拥有带有 SSD 驱动器和高级许可证的 DAS 存储，新安装中就会自动启用类似AFF的特性。

凭借类似AFF的特性，以下内联 SE 功能会在安装过程中自动启用：

* 内联零模式检测
* 卷内联重复数据删除
* 卷后台重复数据删除
* 自适应内联压缩
* 内联数据压缩
* 聚合内联重复数据删除
* 聚合后台重复数据删除


要验证ONTAP Select是否已启用所有默认存储效率策略，请在新创建的卷上运行以下命令：

[listing]
----
<system name>::> set diag
Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y
twonode95IP15::*> sis config
Vserver:                                SVM1
Volume:                                 _export1_NFS_volume
Schedule                                -
Policy:                                 auto
Compression:                            true
Inline Compression:                     true
Compression Type:                       adaptive
Application IO Si                       8K
Compression Algorithm:                  lzopro
Inline Dedupe:                          true
Data Compaction:                        true
Cross Volume Inline Deduplication:      true
Cross Volume Background Deduplication:  true
----

NOTE: 要从 9.6 及更高版本升级ONTAP Select ，您必须使用高级许可证在 DAS SSD 存储上安装ONTAP Select 。此外，在使用ONTAP Deploy 进行初始集群安装时，您必须选中“启用存储效率”复选框。如果先前的条件尚未满足，则在ONTAP升级后启用类似AFF的个性化功能需要手动创建启动参数并重新启动节点。请联系技术支持了解更多详细信息。

.ONTAP Select存储效率配置
下表总结了可用的各种存储效率选项，这些选项默认启用，或默认未启用但建议启用，具体取决于媒体类型和软件许可证。

[cols="4"]
|===
| ONTAP Select功能 | DAS SSD（高级版或高级 XL^1^） | DAS HDD（所有许可证） | vNAS（所有许可证） 


| 在线零点检测 | 是（默认） | 是 由用户按卷启用 | 是 由用户按卷启用 


| 卷内联重复数据删除 | 是（默认） | 不可用 | 不支持 


| 32K 内联压缩（二次压缩） | 是 由用户根据每个卷启用。 | 是 由用户按卷启用 | 不支持 


| 8K 内联压缩（自适应压缩） | 是（默认） | 是 由用户根据卷启用 | 不支持 


| 后台压缩 | 不支持 | 是 由用户根据卷启用 | 是 由用户按卷启用 


| 压缩扫描仪 | 是 | 是 | 是 由用户按卷启用 


| 内联数据压缩 | 是（默认） | 是 由用户根据卷启用 | 不支持 


| 压实扫描仪 | 是 | 是 | 不支持 


| 聚合内联重复数据删除 | 是（默认） | 不适用 | 不支持 


| 卷后台重复数据删除 | 是（默认） | 是 由用户根据卷启用 | 是 由用户按卷启用 


| 聚合后台重复数据删除 | 是（默认） | 不适用 | 不支持 
|===
[small]#^1^ ONTAP Select 9.6 支持新的许可证（Premium XL）和新的虚拟机大小（Large）。但是，大型虚拟机仅支持使用软件 RAID 的 DAS 配置。9.6版本中的大型ONTAP Select虚拟机不支持硬件 RAID 和 vNAS 配置。#

.DAS SSD 配置升级行为注意事项
升级到ONTAP Select 9.6 或更高版本后，请等待…… `system node upgrade-revert show`在验证现有卷的存储效率值之前，发出命令指示升级已完成。

在升级到ONTAP Select 9.6 或更高版本的系统上，在现有聚合或新创建的聚合上创建的新卷的行为与在全新部署上创建的卷的行为相同。进行ONTAP Select代码升级的现有卷与新创建的卷具有大部分相同的存储效率策略，但有一些差异：

场景 1:: 如果升级之前卷上未启用任何存储效率策略，则：
+
--
* 有卷 `space guarantee = volume`未启用内联数据压缩、聚合内联去重和聚合后台去重。这些选项可在升级后启用。
* 有卷 `space guarantee = none`未启用后台压缩。此选项可在升级后启用。
* 升级后，现有卷上的存储效率策略设置为自动。


--
场景 2:: 如果在升级之前卷上已经启用了某些存储效率，则：
+
--
* 有卷 `space guarantee = volume`升级后没看出任何区别。
* 有卷 `space guarantee = none`已启用后台聚合去重功能。
* 有卷 `storage policy inline-only`他们的保单设置为自动生效。
* 除了以下卷之外，具有用户自定义存储效率策略的卷的策略不会发生变化： `space guarantee = none` 。这些卷已启用聚合后台重复数据删除。


--

