---
sidebar: sidebar 
permalink: concept_nw_internal_external.html 
keywords: ontap select, internal network, external network 
summary: 内部和外部ONTAP Select网络的特点。 
---
= ONTAP Select内部和外部网络
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select内部和外部网络的特点。



== ONTAP Select内部网络

内部ONTAP Select网络仅存在于产品的多节点版本中，负责为ONTAP Select集群提供集群通信、HA 互连和同步复制服务。此网络包含以下端口和接口：

* *e0c、e0d。*托管集群网络 LIF
* *e0e.*托管 RSM LIF
* *e0f.*托管 HA 互连 LIF


此网络的吞吐量和延迟对于确定ONTAP Select集群的性能和弹性至关重要。为了保证集群安全性并确保系统接口与其他网络流量分开，需要使用网络隔离功能。因此，此网络必须由ONTAP Select集群专用。


NOTE: 不支持将 Select 内部网络用于除 Select 集群流量以外的其他流量（例如应用程序流量或管理流量）。ONTAPONTAPVLAN 上不能有其他虚拟机或主机。

穿越内部网络的网络数据包必须位于带有 VLAN 标记的专用第 2 层网络上。这可以通过完成以下任务之一来实现：

* 将 VLAN 标记的端口组分配给内部虚拟 NIC（e0c 到 e0f）（VST 模式）
* 使用上游交换机提供的本机 VLAN，其中本机 VLAN 不用于任何其他流量（分配没有 VLAN ID 的端口组，即 EST 模式）


在所有情况下，内部网络流量的 VLAN 标记都是在ONTAP Select VM 之外完成的。


NOTE: 仅支持 ESX 标准和分布式 vSwitch。不支持其他虚拟交换机或 ESX 主机之间的直接连接。内部网络必须完全开放；不支持 NAT 或防火墙。

在ONTAP Select集群中，内部流量和外部流量使用称为端口组的虚拟二层网络对象进行隔离。正确分配这些端口组的 vSwitch 至关重要，尤其是对于负责提供集群、高可用性互连和镜像复制服务的内部网络而言。这些网络端口的网络带宽不足会导致性能下降，甚至影响集群节点的稳定性。因此，四节点、六节点和八节点集群要求内部ONTAP Select网络使用 10Gb 连接；不支持 1Gb 网卡。但是，可以对外部网络进行权衡，因为限制流入ONTAP Select集群的数据流不会影响其可靠运行的能力。

双节点集群可以使用四个 1Gb 端口进行内部流量传输，也可以使用一个 10Gb 端口，而无需像四节点集群那样使用两个 10Gb 端口。如果服务器环境不适合安装四个 10Gb NIC 卡，则可以将两个 10Gb NIC 卡用于内部网络，将两个 1Gb NIC 卡用于外部ONTAP网络。



=== 内部网络验证和故障排除

可以使用网络连接检查器功能来验证多节点集群中的内部网络。可以通过运行 Deploy CLI 来调用此函数。 `network connectivity-check start`命令。

运行以下命令查看测试的输出：

[listing]
----
network connectivity-check show --run-id X (X is a number)
----
此工具仅适用于对多节点 Select 集群中的内部网络进行故障排除。不应用于排除单节点集群（包括 vNAS 配置）、 ONTAP Deploy 到ONTAP Select 的连接问题或客户端连接问题。

集群创建向导（ ONTAP Deploy UI 的一部分）包含内部网络检查器，作为创建多节点集群期间可用的可选步骤。鉴于内部网络在多节点集群中发挥的重要作用，将此步骤作为集群创建工作流的一部分可以提高集群创建操作的成功率。

从ONTAP Deploy 2.10 开始，内部网络使用的 MTU 大小可以设置在 7,500 到 9,000 之间。网络连接检查器也可用于测试 7,500 到 9,000 之间的 MTU 大小。默认 MTU 值设置为虚拟网络交换机的值。如果环境中存在 VXLAN 等网络覆盖，则必须将该默认值替换为较小的值。



== ONTAP Select外部网络

ONTAP Select外部网络负责集群的所有出站通信，因此在单节点和多节点配置中均存在。虽然此网络不像内部网络那样具有严格定义的吞吐量要求，但管理员应注意不要在客户端和ONTAP虚拟机之间造成网络瓶颈，因为性能问题可能会被误认为是ONTAP Select问题。


NOTE: 与内部流量类似，外部流量可以在 vSwitch 层 (VST) 和外部交换机层 (EST) 进行标记。此外，外部流量还可以由ONTAP Select虚拟机本身通过称为 VGT 的过程进行标记。请参阅该部分link:concept_nw_data_mgmt_separation.html["数据和管理流量分离"]更多详情请见下文。

下表重点介绍了ONTAP Select内部和外部网络之间的主要区别。

*内部网络与外部网络快速参考*

[cols="3*"]
|===
| 描述 | 内部网络 | 外部网络 


| 网络服务 | 集群 HA/IC RAID SyncMirror (RSM) | 集群间数据管理（SnapMirror和SnapVault） 


| 网络隔离 | 必填项 | 可选 


| 帧大小（MTU） | 7,500 至 9,000 | 1,500（默认）9,000（支持） 


| IP地址分配 | 自动生成 | 用户定义 


| DHCP 支持 | 否 | 否 
|===


=== NIC 组合

为了确保内部和外部网络均具备提供高性能和容错能力所需的带宽和弹性特性，建议使用物理网络适配器绑定。支持具有单个 10Gb 链路的双节点集群配置。但是， NetApp建议的最佳实践是在ONTAP Select集群的内部和外部网络上都使用 NIC 绑定。



=== MAC 地址生成

分配给所有ONTAP Select网络端口的 MAC 地址均由随附的部署实用程序自动生成。该实用程序使用NetApp特有的平台特定组织唯一标识符 (OUI)，以确保不与FAS系统冲突。之后，此地址的副本将存储在ONTAP Select安装虚拟机 (ONTAP Deploy) 的内部数据库中，以防止在未来的节点部署过程中意外重新分配。管理员在任何情况下都不应修改已分配的网络端口 MAC 地址。
