---
sidebar: sidebar 
permalink: concept_ots_deploy.html 
keywords: ontap select deploy, deploy administration utility, deploy utility, functionality, accessing 
summary: ONTAP Select Deploy 是一款用于部署和管理ONTAP Select集群的管理实用程序。Deploy 
---
= ONTAP Select Deploy
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Select Deploy 是一款用于部署和管理ONTAP Select集群的管理实用程序。Deploy打包为 Linux 虚拟机，您必须在创建ONTAP Select集群之前安装它。



== 核心功能

Deploy 管理实用程序执行以下核心功能：

* 记录部署ONTAP Select 的每个虚拟机管理程序主机的详细信息
* 配置主机并安装所需的许可证
* 部署和管理ONTAP Select集群
* 维护ONTAP Select集群和主机的清单
* 收集AutoSupport数据并将其发送到NetApp
* 维护一组内部ONTAP Select节点映像
* 支持虚拟机管理程序特定的命令格式和协议




== 访问部署实用程序的方法

访问 Deploy 管理实用程序时，您有多个选项可用。所有外部接口的功能相同。您应该选择最符合您特定部署目标和要求的访问选项。在所有情况下，您都必须使用管理员帐户和有效密码登录。



=== Web图形用户界面

您可以通过现代 Web 浏览器访问 Deploy 实用程序。WebUI 提供了直观易用的界面，在大多数情况下，它将是您使用该实用程序时的主要界面。



=== 命令行界面

可通过管理 Shell 访问基于文本的命令行界面。您可以通过以下方式访问 CLI 管理 Shell：

* 安全外壳 (SSH)
* 虚拟机控制台


您通常会在安装和初始配置过程中使用虚拟机控制台。但是，在大多数情况下，SSH 提供了更灵活、更便捷的选项。



=== REST Web 服务 API

向外部客户端公开的 REST Web 服务 API 为连接到 Deploy 实用程序提供了另一种选择。您可以使用任何支持 REST Web 服务的主流编程语言或工具来访问该 API。常用的选择包括：

* Python
* Java
* 卷曲


使用编程或脚本语言可以实现ONTAP Select集群部署和管理的自动化。



=== ONTAP Select在线文档网页

在 Deploy 实用程序中显示在线文档网页是访问 REST Web 服务 API 的另一种方法。但是，您无需使用编程语言，而是使用浏览器通过页面访问管理 API。提供以下功能：

* REST Web 服务 API 中每个调用的详细描述
* 手动发出任何 API 调用的能力


您可以使用 Deploy 虚拟机的 IP 或域名访问在线文档页面。要显示该页面，请在浏览器中输入以下格式的 URL（将 URL 替换为您的 Deploy VM 实例的相应 IP 地址或域名）： `\http://<ip_address>/api/ui`
