---
sidebar: sidebar 
permalink: concept_lic_cp_operation.html 
keywords: license, licensing, Capacity Pools, operation details 
summary: 容量池许可模型与容量层模型不同。它不是为每个节点分配专用的存储容量，而是将存储容量分配给一个池，并在多个节点之间共享。为了支持容量池模型，我们创建了其他组件和流程。 
---
= ONTAP Select容量池许可模式的操作详细信息
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
容量池许可模型与容量层模型不同。它不是为每个节点分配专用的存储容量，而是将存储容量分配给一个池，并在多个节点之间共享。为了支持容量池模型，我们创建了其他组件和流程。



== 许可证管理器

许可证管理器在每个 Deploy 管理实用程序实例中作为单独的进程运行。许可证管理器提供的一些功能包括：

* 根据容量池许可证序列号为每个节点生成唯一的二十位序列号
* 根据ONTAP Select节点的请求，从共享容量池创建容量租约
* 通过 Deploy 用户界面报告池使用情况信息




== 租赁特征

使用容量池许可证的节点上为每个数据聚合分配的存储必须具有关联的租约。节点请求存储租约，如果容量可用，许可证管理器将以租约进行响应。每个租约都具有以下显式或隐式属性：

* 许可证管理器 每个ONTAP Select节点都与一个许可证管理器实例关联
* 容量池 每个ONTAP Select节点都与一个容量池关联
* 存储分配 租约中分配特定的容量值
* 到期日期和时间租约期限为一小时至七天，具体取决于用户配置。




== 许可证锁定ID

每个许可证管理器实例，以及每个相应的 Deploy 实用程序实例，都使用一个唯一的 128 位编号进行标识。此编号与九位数容量池许可证序列号相结合，将池锁定到特定的许可证管理器实例（实际上是一个 Deploy 实例）。您必须在NetApp支持站点生成NetApp许可证文件 (NLF) 时提供这两个值。

您可以通过以下方式使用 Web 用户界面确定 Deploy 实例的许可证锁定 ID：

* 首次登录 Deploy 时会显示此页面。您也可以点击页面右上角的下拉框并选择“开始使用”来显示此页面。LLID显示在“添加许可证”部分。
* 管理 单击页面顶部的“*管理*”选项卡，然后单击“*系统*”和“*设置*”。




== 基本租赁业务

每次创建、扩展或更改数据聚合时， ONTAP Select节点都必须查找或请求有效的容量租约。可以使用之前请求中获取的仍然有效的租约，也可以根据需要请求新的租约。ONTAPONTAP Select节点执行以下步骤来查找容量池租约：

. 如果节点上存在现有租约，则只要满足以下所有条件，就会使用该租约：
+
** 租约尚未到期
** 聚合的存储请求未超出租赁容量


. 如果找不到现有租约，节点将向许可证管理器请求新的租约。




== 将存储容量返回到容量池

存储容量根据需要从容量池中分配，每个新请求都会减少池中的可用存储空间。存储容量在以下几种情况下会返回到池中：

* 数据聚合的租约已到期，且节点未续订
* 数据集合已删除



NOTE: 如果删除ONTAP Select虚拟机，所有活动租约仍然有效，直至到期。到期后，容量将返回到池中。
