---
sidebar: sidebar 
permalink: reference_api_workflow01.html 
keywords: rest api, deploy rest api, rest, workflow, create cluster, curl, json 
summary: 您可以在由 vCenter 管理的 VMware ESXi 主机上部署单节点ONTAP Select集群。该集群是使用评估许可证创建的。 
---
= 工作流程 1：在 ESXi 上创建ONTAP Select单节点评估集群
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在由 vCenter 管理的 VMware ESXi 主机上部署单节点ONTAP Select集群。该集群是使用评估许可证创建的。

集群创建工作流程在以下情况下有所不同：

* ESXi 主机不受 vCenter 管理（独立主机）
* 集群内使用多个节点或主机
* 集群已部署在生产环境中，并已购买许可证
* 使用 KVM 虚拟机管理程序代替 VMware ESXi




== 1.注册 vCenter 服务器凭据

部署到由 vCenter 服务器管理的 ESXi 主机时，必须在注册主机之前添加凭据。然后，Deploy 管理实用程序可以使用该凭据向 vCenter 进行身份验证。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 部署 | POST | /安全/凭证 
|===
卷曲::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step01 'https://10.21.191.150/api/security/credentials'
----
JSON 输入（步骤 1）::


[source, json]
----
{
  "hostname": "vcenter.company-demo.com",
  "type": "vcenter",
  "username": "misteradmin@vsphere.local",
  "password": "mypassword"
}
----
加工类型:: 异步
输出::
+
--
* 位置响应标头中的凭证 ID
* 作业对象


--




== 2.注册虚拟机管理程序主机

您必须添加一个虚拟机管理程序主机，其中包含ONTAP Select节点的虚拟机将在该主机上运行。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | POST | /主机 
|===
卷曲::


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step02 'https://10.21.191.150/api/hosts'
----
JSON 输入（步骤 2）::


[source, json]
----
{
  "hosts": [
    {
      "hypervisor_type": "ESX",
      "management_server": "vcenter.company-demo.com",
      "name": "esx1.company-demo.com"
    }
  ]
}
----
加工类型:: 异步
输出::
+
--
* 位置响应标头中的主机 ID
* 作业对象


--




== 3.创建集群

创建ONTAP Select集群时，将注册基本集群配置并由 Deploy 自动生成节点名称。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | POST | /集群 
|===
卷曲:: 对于单节点集群，查询参数 node_count 应设置为 1。


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step03 'https://10.21.191.150/api/clusters? node_count=1'
----
JSON 输入（步骤 3）::


[source, json]
----
{
  "name": "my_cluster"
}
----
加工类型:: 同步
输出::
+
--
* 位置响应标头中的集群 ID


--




== 4.配置集群

在配置集群时，您必须提供几个属性。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | 修补 | /集群/{cluster_id} 
|===
卷曲:: 您必须提供集群 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step04 'https://10.21.191.150/api/clusters/CLUSTERID'
----
JSON 输入（步骤 4）::


[source, json]
----
{
  "dns_info": {
    "domains": ["lab1.company-demo.com"],
    "dns_ips": ["10.206.80.135", "10.206.80.136"]
    },
    "ontap_image_version": "9.5",
    "gateway": "10.206.80.1",
    "ip": "10.206.80.115",
    "netmask": "255.255.255.192",
    "ntp_servers": {"10.206.80.183"}
}
----
加工类型:: 同步
输出:: 无




== 5.检索节点名称

创建集群时，Deploy 管理实用程序会自动生成节点标识符和名称。您必须先检索分配的 ID，然后才能配置节点。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | GET | /集群/{cluster_id}/节点 
|===
卷曲:: 您必须提供集群 ID。


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/clusters/CLUSTERID/nodes?fields=id,name'
----
加工类型:: 同步
输出::
+
--
* 数组记录每个描述具有唯一 ID 和名称的单个节点


--




== 6.配置节点

您必须提供节点的基本配置，这是用于配置节点的三个 API 调用中的第一个。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | 路径 | /集群/{cluster_id}/节点/{node_id} 
|===
卷曲:: 您必须提供集群 ID 和节点 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step06 'https://10.21.191.150/api/clusters/CLUSTERID/nodes/NODEID'
----
JSON 输入（步骤 6）:: 您必须提供ONTAP Select节点将运行的主机 ID。


[source, json]
----
{
  "host": {
    "id": "HOSTID"
    },
  "instance_type": "small",
  "ip": "10.206.80.101",
  "passthrough_disks": false
}
----
加工类型:: 同步
输出:: 无




== 7.检索节点网络

您必须识别单节点集群中节点使用的数据和管理网络。单节点集群不使用内部网络。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | GET | /集群/{cluster_id}/节点/{node_id}/网络 
|===
卷曲:: 您必须提供集群 ID 和节点 ID。


[source, curl]
----
curl -iX GET -u admin:<password> -k 'https://10.21.191.150/api/ clusters/CLUSTERID/nodes/NODEID/networks?fields=id,purpose'
----
加工类型:: 同步
输出::
+
--
* 两条记录的数组，每条记录描述节点的单个网络，包括唯一 ID 和用途


--




== 8.配置节点网络

您必须配置数据和管理网络。单节点集群不使用内部网络。


NOTE: 发出以下 API 调用两次，每个网络一次。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | 修补 | /集群/{cluster_id}/节点/{node_id}/网络/{network_id} 
|===
卷曲:: 您必须提供集群 ID、节点 ID 和网络 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step08 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID/networks/NETWORKID'
----
JSON 输入（步骤 8）:: 您需要提供网络的名称。


[source, json]
----
{
  "name": "sDOT_Network"
}
----
加工类型:: 同步
输出:: 无




== 9.配置节点存储池

配置节点的最后一步是连接存储池。您可以通过 vSphere Web Client 或 Deploy REST API 确定可用的存储池。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | 修补 | /集群/{cluster_id}/节点/{node_id}/网络/{network_id} 
|===
卷曲:: 您必须提供集群 ID、节点 ID 和网络 ID。


[source, curl]
----
curl -iX PATCH -H 'Content-Type: application/json' -u admin:<password> -k -d @step09 'https://10.21.191.150/api/clusters/ CLUSTERID/nodes/NODEID'
----
JSON 输入（步骤 9）:: 池容量为 2 TB。


[source, json]
----
{
  "pool_array": [
    {
      "name": "sDOT-01",
      "capacity": 2147483648000
    }
  ]
}
----
加工类型:: 同步
输出:: 无




== 10.部署集群

集群和节点配置完成后，就可以部署集群了。

[cols="15,15,70"]
|===
| 类别 | HTTP 动词 | 路径 


| 集群 | POST | /集群/{cluster_id}/部署 
|===
卷曲:: 您必须提供集群 ID。


[source, curl]
----
curl -iX POST -H 'Content-Type: application/json' -u admin:<password> -k -d @step10 'https://10.21.191.150/api/clusters/CLUSTERID/deploy'
----
JSON 输入（步骤 10）:: 您必须提供ONTAP管理员帐户的密码。


[source, json]
----
{
  "ontap_credentials": {
    "password": "mypassword"
  }
}
----
加工类型:: 异步
输出::
+
--
* 作业对象


--


.相关信息
link:deploy-evaluation-ontap-select-ovf-template.html["部署ONTAP Select集群的 90 天评估实例"]
