---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: 您应考虑几个与ONTAP Select主机存储相关的规划问题。 
---
= ONTAP Select存储和 RAID 注意事项
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您应考虑几个与ONTAP Select主机存储相关的规划问题。


NOTE: 外部存储支持信息概述如下：link:reference_plan_ots_vnas.html["ONTAP Select vNAS 要求"] 。



== 硬件 RAID 控制器要求

部署ONTAP Select 的虚拟机管理程序主机上的 RAID 控制器必须满足几个要求。


NOTE: 在使用硬件 RAID 控制器或ONTAP Select提供的软件 RAID 功能时，运行ONTAP Select 的主机需要本地物理驱动器。如果您使用ONTAP Select vNAS 解决方案访问外部存储，则不会使用本地 RAID 控制器和软件 RAID 功能。

RAID 控制器的最低要求包括：

* 12 Gbps 吞吐量
* 512 MB 内部电池供电或闪存（超级电容）缓存
* 以回写模式配置：
+
** 启用故障回复模式以“直写”（如果支持）
** 启用“始终预读”策略（如果支持）


* RAID 控制器后面的所有本地磁盘都应配置为单个 RAID 组；如果需要，可以使用多个 RAID 控制器：
+
** 禁用 RAID 组的本地驱动器缓存，这对于维护数据完整性至关重要。


* 必须根据以下准则执行 LUN 配置：
+
** 如果 RAID 组大小超过最大 LUN 大小 64 TB，则应配置多个大小相同的 LUN，以使用 RAID 组内的所有可用存储空间。
** 如果 RAID 组大小小于最大 LUN 大小 64 TB，则应配置一个使用 RAID 组内所有可用存储空间的 LUN。






== 软件 RAID 要求

在虚拟机管理程序上部署ONTAP Select集群时，您可以利用ONTAP Select提供的软件 RAID 功能，而无需使用本地硬件 RAID 控制器。在使用软件 RAID 部署集群之前，您必须注意一些要求和限制。



=== 一般要求

软件 RAID 部署环境必须满足以下核心要求：

* VMware ESXi 7.0 GA（内部版本 15843807）或更高版本
* ONTAP Select Premium 许可证或更高版本
* 仅限本地 SSD 驱动器
* 将系统磁盘与根和数据聚合分离
* 主机上没有硬件 RAID 控制器



NOTE: 如果存在硬件 RAID 控制器，请参阅link:concept_stor_concepts_chars.html["深层存储"]本节用于说明其他配置要求。



=== ESXi 特定要求

* VMware ESXi 7.0 GA（内部版本 15843807）或更高版本
* 不支持 VMware VMotion、HA 和 DRS
* 您无法将软件 RAID 与从ONTAP Select 9.4 或更早版本升级的节点一起使用。如果是这种情况，您需要创建一个新节点来部署软件 RAID。




=== KVM 特定要求

还有一些特定的软件包配置要求。参见link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["Linux 服务器的准备"]了解更多信息，请执行以下步骤。

媒体对 KVM 的期望:: 所使用的 SSD 闪存设备必须满足以下额外要求：
+
--
* SSD 设备必须通过以下方法准确、持续地向 Linux 主机报告自身情况：
+
** # cat /sys/block/<设备>/queue/rotational
+
这些命令报告的值必须为“0”。



* 预计设备将连接到 HBA，或者在某些情况下连接到配置为 JBOD 模式的 RAID 控制器。使用 RAID 控制器时，设备功能必须通过主机传递，且不得覆盖任何 RAID 功能。在 JBOD 模式下使用 RAID 控制器时，您应该查看 RAID 文档或根据需要联系供应商，以确保设备将转速报告为“0”。
* 有两个独立的存储组件：
+
** 虚拟机存储
+
这是一个 LVM 池（存储池），包含用于托管ONTAP Select虚拟机的系统数据。该 LVM 池必须由高耐用性闪存设备支持，可以是 SAS、SATA 或 NVMe。建议使用 NVMe 设备以提高性能。

** 数据磁盘
+
这是一组用于数据管理的 SAS 或 SATA SSD 驱动器。SSD设备应为企业级且耐用。不支持 NVMe 接口。



* 所有设备必须采用 512BPS 格式化。


--




=== ONTAP Select节点配置

您必须按如下方式配置每个ONTAP Select节点和虚拟机管理程序主机，以将系统磁盘与根和数据聚合分开：

* 创建系统存储池您必须为ONTAP Select系统数据创建一个存储池。您必须在配置ONTAP Select节点的过程中连接存储池。
* 连接必要的物理磁盘 虚拟机管理程序主机必须连接所需的 SSD 磁盘，并且可供ONTAP Select虚拟机使用。这些驱动器用于存储根聚合和数据聚合。您必须在配置ONTAP Select节点的过程中连接存储磁盘。




== 存储容量限制

作为规划ONTAP Select部署的一部分，您应该了解与存储分配和使用相关的限制。

最重要的存储限制如下。您还应该查看link:https://mysupport.netapp.com/matrix/["互操作性表工具"^]更多详细信息，敬请垂询。


TIP: ONTAP Select强制实施多项与存储分配和使用相关的限制。在部署ONTAP Select集群或购买许可证之前，您应该熟悉这些限制。参见link:https://docs.netapp.com/us-en/ontap-select/concept_lic_evaluation.html["许可证"]更多信息请参见相关部分。



=== 计算原始存储容量

ONTAP Select存储容量对应于连接到ONTAP Select虚拟机的虚拟数据磁盘和根磁盘的总允许大小。分配容量时应考虑这一点。



=== 单节点集群的最小存储容量

单节点集群中为节点分配的存储池最小大小为：

* 评估：500 GB
* 生产：1.0 TB


生产部署的最低分配包括 1 TB 用于用户数据，加上各种ONTAP Select内部进程使用的约 266 GB，这被视为必需的开销。



=== 多节点集群的最小存储容量

多节点集群中每个节点分配的存储池最小大小为：

* 评估：1.9 TB
* 生产：2.0 TB


生产部署的最低分配包括 2 TB 用于用户数据，加上各种ONTAP Select内部进程使用的约 266 GB，这被视为必需的开销。

[NOTE]
====
HA 对中的每个节点必须具有相同的存储容量。

估算 HA 对的存储量时，必须考虑所有聚合（根聚合和数据聚合）都已镜像。因此，聚合的每个丛都会消耗相同的存储量。

例如，创建 2 TB 聚合时，它会将 2 TB 分配给两个 plex 实例（plex0 为 2 TB，plex1 为 2 TB），或将总许可存储量的 4 TB 分配给两个 plex 实例。

====


=== 存储容量和多个存储池

在使用本地直连存储、VMware vSAN 或外部存储阵列时，您可以将每个ONTAP Select节点配置为使用最多 400 TB 的存储空间。但是，在使用直连存储或外部存储阵列时，单个存储池的最大大小为 64 TB。因此，如果您计划在这些情况下使用超过 64 TB 的存储空间，则必须按如下方式分配多个存储池：

* 在集群创建过程中分配初始存储池
* 通过分配一个或多个额外的存储池来增加节点存储



NOTE: 每个存储池中都会留出 2% 的缓冲区未使用，并且无需容量许可证。上限，否则ONTAP Select不会使用此存储空间。如果指定了容量上限，则将使用该存储空间，除非指定的容量在 2% 的缓冲区内。需要此缓冲区是为了防止在尝试分配存储池中的所有空间时偶尔发生的错误。



=== 存储容量和 VMware vSAN

使用 VMware vSAN 时，数据存储区可以大于 64 TB。但是，创建ONTAP Select集群时，您最初最多只能分配 64 TB 的存储空间。集群创建完成后，您可以从现有的 vSAN 数据存储区分配额外的存储空间。ONTAPONTAP Select可使用的 vSAN 数据存储区容量取决于虚拟机存储策略集。



=== 最佳实践

您应该考虑有关虚拟机管理程序核心硬件的以下建议：

* 单个ONTAP Select聚合中的所有驱动器应为同一类型。例如，不应在同一个聚合中混用 HDD 驱动器和 SSD 驱动器。




== 根据平台许可证的额外磁盘驱动器要求

根据平台许可证的提供，您选择的驱动器受到限制。


NOTE: 使用本地 RAID 控制器和驱动器以及软件 RAID 时，磁盘驱动器要求适用。这些要求不适用于通过ONTAP Select vNAS 解决方案访问的外部存储。

.标准
* 8 到 60 个内部 HDD（NL-SAS、SATA、10K SAS）


.高级
* 8 到 60 个内部 HDD（NL-SAS、SATA、10K SAS）
* 4 至 60 个内部 SSD


.高级加大码
* 8 到 60 个内部 HDD（NL-SAS、SATA、10K SAS）
* 4 至 60 个内部 SSD
* 4 到 14 个内部 NVMe



NOTE: 高级许可证（仅限 SSD）和高级 XL 许可证（SSD 或 NVMe）支持带有本地 DAS 驱动器的软件 RAID。



== 带有软件 RAID 的 NVMe 驱动器

您可以配置软件 RAID 以使用 NVMe SSD 驱动器。您的环境必须满足以下要求：

* 使用受支持的部署管理实用程序ONTAP Select
* Premium XL 平台许可证或 90 天评估许可证
* VMware ESXi 6.7 或更高版本
* 符合规范 1.0 或更高版本的 NVMe 设备


您需要在使用 NVMe 驱动器之前手动配置它们。看link:task_chk_nvme_configure.html["配置主机以使用 NVMe 驱动器"]了解更多信息。
