---
sidebar: sidebar 
permalink: reference_plan_dep_general.html 
keywords: plan, planning, ontap select deploy, general requirements 
summary: 在计划安装ONTAP Select Deploy 管理实用程序时，您应该考虑几个常规要求。 
---
= ONTAP Select Deploy 的一般要求和规划
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在计划安装ONTAP Select Deploy 管理实用程序时，您应该考虑几个常规要求。



== 将 Deploy 实用程序与ONTAP Select集群配对

将 Deploy 实用程序实例与ONTAP Select集群配对时，您有多种选择。


NOTE: 在所有部署方案中，单个ONTAP Select集群及其中的节点只能由一个 Deploy 管理实用程序实例进行管理。一个集群不能由两个或多个不同的 Deploy 实用程序实例进行管理。

.每个ONTAP Select集群对应一个实用程序实例
您可以使用 Deploy 实用程序的专用实例来部署和管理每个ONTAP Select集群。通过这种一对一配置，每个实用程序与集群之间的配对都有明确的区分。此配置可提供高级别的隔离，并缩小故障域。

.适用于多个ONTAP Select集群的实用程序的一个实例
您可以使用单个 Deploy 实用程序实例在组织中部署和管理多个ONTAP Select集群。通过这种一对多配置，所有处理和配置数据均由同一个 Deploy 实用程序实例管理。


NOTE: Deploy 实用程序的一个实例最多可以管理 400 个ONTAP Select节点或 100 个集群。



== 与 KVM 环境相关的要求

在 KVM 虚拟机管理程序环境中安装 Deploy 管理实用程序之前，您应该查看基本要求并为部署做好准备。

.部署的要求和限制
在 KVM 环境中安装ONTAP Select Deploy 实用程序时，应考虑一些要求和限制。

.Linux KVM 主机服务器硬件要求
Linux KVM 虚拟机管理程序主机必须满足几个最低资源要求。请验证部署ONTAP Select 的主机是否满足以下基本要求：

* Linux 服务器：
+
** 硬件和软件必须是 64 位
** 服务器必须遵守为ONTAP Select节点定义的相同支持版本


* 虚拟 CPU (2)
* 虚拟内存（4GB）
* 存储空间（40GB）
* “动态主机配置协议（DHCP）已启用（您也可以分配静态 IP 地址）


.网络连接
验证 Deploy 虚拟机网络接口是否已配置并可以连接到其管理的ONTAP Select主机。

.支持 IP 版本 4
ONTAP Select Deploy 仅支持 IP 版本 4 (IPv4)。不支持 IP 版本 6 (IPv6)。此限制会以以下方式影响ONTAP Select ：

* 您必须为 Deploy VM 的管理 LIF 分配一个 IPv4 地址。
* Deploy 无法创建配置为在ONTAP LIF 上使用 IPv6的 ONTAP Select节点。




== 必需的配置信息

作为部署规划的一部分，您应该在安装ONTAP Select Deploy 管理实用程序之前确定所需的配置信息。

.部署虚拟机的名称
VM 使用的名称。

.Linux KVM 主机的名称
安装了 Deploy 实用程序的 Linux KVM 主机。

.存储池名称
保存 VM 文件的存储池（大约需要 40GB）。

.虚拟机的网络
Deploy VM 所连接的网络。



== 可选的网络配置信息

Deploy VM 默认使用 DHCP 配置。但是，如果需要，您可以手动配置 VM 的网络接口。

.主机名
主持人的姓名。

.主机 IP 地址
静态 IPv4 地址。

.子网掩码
子网掩码，基于虚拟机所属的网络。

.网关
默认网关或路由器。

.主 DNS 服务器
主域名服务器。

.辅助 DNS 服务器
辅助域名服务器。

.搜索域名
要使用的搜索域。



== 使用凭证存储进行身份验证

ONTAP Select Deploy 凭据存储是一个保存帐户信息的数据库。Deploy使用帐户凭据在集群创建和管理过程中执行主机身份验证。您应该了解如何在规划ONTAP Select部署时使用凭据存储。


NOTE: 账户信息使用AES加密算法和SHA-256哈希算法安全地存储在数据库中。

.凭证类型
支持以下类型的凭证：

* 主机 用于在将ONTAP Select节点直接部署到 VMware ESXi 的过程中对虚拟机管理程序主机进行身份验证
* vCenter 当主机由 VMware vCenter 管理时，用于在将ONTAP Select节点部署到 ESXi 的过程中对 vCenter 服务器进行身份验证


.使用权
在使用 Deploy 执行常规管理任务（例如添加虚拟机管理程序主机）时，可以从内部访问凭据存储。您也可以直接通过 Deploy Web 用户界面和 CLI 管理凭据存储。
