---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 如果ONTAP Select Deploy 实用程序因某种原因发生故障或不可用，您将无法管理ONTAP Select节点和集群。此外，所有双节点集群都会失去 HA 功能，因为 Deploy 附带的调解器服务不可用。如果发生不可恢复的故障，您必须恢复 Deploy 实用程序实例才能恢复管理和 HA 功能。 
---
= 恢复双节点集群的ONTAP Select Deploy 实用程序
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果ONTAP Select Deploy 实用程序因某种原因发生故障或不可用，您将无法管理ONTAP Select节点和集群。此外，所有双节点集群都会失去 HA 功能，因为 Deploy 附带的调解器服务不可用。如果发生不可恢复的故障，您必须恢复 Deploy 实用程序实例才能恢复管理和 HA 功能。



== 准备恢复部署实用程序

在尝试恢复 Deploy 实用程序实例之前，您需要做好准备以确保成功。您必须熟悉若干行政程序并掌握所需信息。

.步骤
. 确认您可以在虚拟机管理程序环境中安装ONTAP Select Deploy 实用程序的新实例。
+
link:task_install_deploy.html["了解如何安装ONTAP Select Deploy 实用程序"]

. 确认您可以登录到ONTAP Select集群并访问ONTAP集群 shell (CLI)。
. 确定您是否拥有包含ONTAP Select双节点集群的失败部署实用程序实例的配置数据备份。您可能拥有不包含该集群的备份。
. 根据所使用的恢复程序，验证是否可以恢复部署配置数据的备份。
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["了解如何将部署配置数据恢复到新的虚拟机"]

. 您拥有发生故障的原始部署实用程序虚拟机的 IP 地址。
. 确定采用容量池许可还是容量层级许可。如果使用容量池许可，则必须在恢复或还原 Deploy 实例后重新安装每个容量池许可证。
. 决定在恢复ONTAP Select Deploy 实用程序实例时使用哪个程序。您的决定取决于您是否拥有包含ONTAP Select双节点集群的原始故障 Deploy 实用程序的配置数据备份。
+
[cols="35,65"]
|===
| 您是否有包含双节点集群的 Deploy 备份？ | 使用恢复程序…… 


| 是 | <<restore-deploy-backup,使用配置备份恢复 Deploy 实用程序实例>> 


| 否 | <<restore-and-recover-deploy,重新配置并恢复 Deploy 实用程序实例>> 
|===




== 使用配置备份恢复 Deploy 实用程序实例

如果您拥有包含双节点集群的故障 Deploy 实用程序实例的备份，则可以将配置数据还原到新的 Deploy 虚拟机实例。然后，您必须通过对ONTAP Select集群中的两个节点执行额外配置来完成恢复。

.开始之前
备份包含双节点集群的原始部署失败虚拟机的配置数据。您必须能够登录双节点集群的ONTAP CLI，并且知道这两个节点的ONTAP名称。

.关于此任务
由于您恢复的配置备份包含双节点集群，因此将在新的 Deploy 实用程序虚拟机中重新创建中介 iSCSI 目标和邮箱。

.步骤
. 准备ONTAP Select Deploy 实用程序的新实例：
+
.. 安装新的 Deploy 实用程序虚拟机。
.. 将 Deploy 配置从以前的备份恢复到新的虚拟机。
+
有关安装和恢复过程的更多详细信息，请参阅相关任务。



. Sign inONTAP Select双节点集群的ONTAP命令行界面。
. 进入高级权限模式：
+
[source, cli]
----
set adv
----
. 如果新部署虚拟机的 IP 地址与原部署虚拟机的 IP 地址不同，请删除旧的中介 iSCSI 目标并添加新目标：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
这 `<ip_address>`参数是新部署虚拟机的 IP 地址。

+
这些命令允许ONTAP Select节点发现新 Deploy 实用程序虚拟机上的邮箱磁盘。

. 确定中介磁盘的名称：
+
[source, cli]
----
disk show -container-type mediator
----
. 将邮箱磁盘分配给两个节点：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 验证存储故障转移是否已启用：
+
[source, cli]
----
storage failover show
----


.完成后
如果您使用容量池许可，请重新安装每个容量池许可证。看link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安装容量池许可证"]更多详情请见下文。



== 重新配置并恢复 Deploy 实用程序实例

如果您没有包含双节点集群的失败部署实用程序实例的备份，请在新的部署虚拟机中配置中介 iSCSI 目标和邮箱。然后，通过对ONTAP Select集群中的两个节点进行额外配置来完成恢复。

.开始之前
请确认您已获取新部署实用程序实例的中介目标名称。您必须能够登录双节点集群的ONTAP CLI，并且知道这两个节点的ONTAP名称。

.关于此任务
即使新的 Deploy 虚拟机不包含双节点集群，您也可以选择将配置备份还原到该虚拟机。由于还原操作不会重新创建双节点集群，因此您必须通过 Deploy 上的ONTAP Select在线文档网页，手动将中介 iSCSI 目标和邮箱添加到新的 Deploy 实用程序实例。您必须能够登录双节点集群，并且知道这两个节点的ONTAP名称。


NOTE: 恢复过程的目标是将双节点集群恢复到健康状态，以便可以执行正常的 HA 接管和交还操作。

.步骤
. 准备ONTAP Select Deploy 实用程序的新实例：
+
.. 安装新的 Deploy 实用程序虚拟机。
.. 可以选择将 Deploy 配置从以前的备份恢复到新的虚拟机。
+
如果您恢复之前的备份，新的 Deploy 实例将不包含双节点集群。有关安装和恢复过程的更多详细信息，请参阅相关信息部分。



. Sign inONTAP Select双节点集群的ONTAP命令行界面。
. 进入高级特权模式：
+
[source, cli]
----
set adv
----
. 获取中介 iSCSI 目标名称：
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. 访问新部署实用程序虚拟机上的在线文档网页并使用管理员帐户登录：
+
`\http://<ip_address>/api/ui`

+
您必须使用 Deploy 虚拟机的 IP 地址。

. 选择 *Mediator*，然后选择 *GET /mediators*。
. 选择“试用！”以显示 Deploy 维护的中介器列表。
+
记下所需中介实例的 ID。

. 选择“中介者”，然后选择“POST”。
. 提供 mediator_id 的值。
. 选择旁边的“型号” `iscsi_target`并填写名称值。
+
使用目标名称作为 iqn_name 参数。

. 选择“试用！”以创建中介 iSCSI 目标。
+
如果请求成功，您将收到 HTTP 状态代码 200。

. 如果新 Deploy 虚拟机的 IP 地址与原始 Deploy 虚拟机不同，则必须使用ONTAP CLI 删除旧的调解器 iSCSI 目标并添加新的目标：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
这 `<ip_address>`参数是新部署虚拟机的 IP 地址。

+
这些命令允许ONTAP Select节点发现新 Deploy 实用程序虚拟机上的邮箱磁盘。

. 确定中介磁盘的名称：
+
[source, cli]
----
disk show -container-type mediator
----
. 将邮箱磁盘分配给两个节点：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 验证存储故障转移是否已启用：
+
[source, cli]
----
storage failover show
----


.完成后
如果您使用容量池许可，请重新安装每个容量池许可证。看link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安装容量池许可证"]更多详情请见下文。
