---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 您可以测试内部集群网络上两个或多个ONTAP Select节点之间的网络连接。通常在部署多节点集群之前运行此测试，以检测可能导致操作失败的问题。 
---
= 确认ONTAP Select节点之间的网络连接
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以测试内部集群网络上两个或多个ONTAP Select节点之间的网络连接。通常在部署多节点集群之前运行此测试，以检测可能导致操作失败的问题。

.开始之前
测试中包含的所有ONTAP Select节点都必须配置并启动。

.关于此任务
每次启动测试时，后台都会创建一个新的流程运行，并为其分配一个唯一的运行标识符。每次只能激活一个运行。

该测试有两种控制其操作的模式：

* 快速：此模式执行基本的无中断测试。将执行 PING 测试，以及网络 MTU 大小和 vSwitch 测试。
* 扩展模式：此模式会对所有冗余网络路径执行更全面的测试。如果在活动的ONTAP Select集群上运行此模式，则可能会影响集群的性能。



NOTE: 建议您在创建多节点集群之前始终执行快速测试。快速测试成功完成后，您可以根据生产需求选择执行扩展测试。

.步骤
. 使用管理员帐户Sign in到 Deploy 实用程序 CLI。
. 显示网络连接检查器的当前运行并验证没有活动运行：
+
`network connectivity-check show`

. 启动网络连接检查器并记下命令输出中的运行标识符：
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
示例

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. 根据运行标识符监控网络连接检查器的进度：
+
`network connectivity-check show -run-id RUN_ID`



.完成后
网络连接检查程序通常会通过删除添加到ONTAP-Internal 端口组的所有临时端口和 IP 地址来进行清理。但是，如果连接性检查器未能移除临时端口，则必须通过重新运行带有相应选项的 CLI 命令来执行手动清理操作。 `-mode cleanup` 。如果不从ONTAP-Internal 端口组中删除临时端口，则可能无法成功创建ONTAP Select虚拟机。
